### PR TITLE
Add GitHub Action for lint, and build

### LINKED ISSUE #15: Add GitHub Action for lint, prettier, build
This issue is a subtask of #12

### PR DESCRIPTION
**Pull request by khattakdev**
Added GitHub actions for **eslint** and **build** on every pull request
This Action is enabled for every branch PR. Later when merging it to the `main` branch, we can restrict it to the `main` branch only.

@eddiejaoude What do you think?

Closes #15

### CODE REVIEW

**Comment by khattakdev** [comment]
Accidentally opened a Pull Request to `main` branch

**Comment by eddiejaoude** [comment]
You can hit `edit` at the top right to update it

**Comment by khattakdev** [comment]
> You can hit `edit` at the top right to update it

That only changes the title. Branches can not be updated

**Comment by eddiejaoude** [comment]
oh that changed, it used to be possible. No problem 🤓

**Comment by nhcarrigan** [comment]
Err, you can still edit it 🤔 

It might be tied to write access, but I don't believe so.

**Comment by eddiejaoude** [comment]
Oh yes for this PR I could not, but for my PR I can... (I learnt something new 👍 )

Screenshot 2021-01-27 at 20 03 23

**Comment by Vyvy-vi** [comment]
Yah, the base branch can be changed :+1: by clicking `edit`
found that out on an issue where Allan commented that this works

**Pull request closed without merging**
